#!bash

. <("$ZENLOG_BIN" -s)

function zenlog_bash_dump_env() {
  echo "---ENV---"
}

preexec() {
  zenlog_bash_preexec
}

prompt_command() {
  lines=$(zenlog_bash_postexec -n)
  echo "Lines: $lines"
}

PS1='\$ '
PS0='$(preexec)'
PROMPT_COMMAND="prompt_command"

tick() {
  local num=${1:-1}
  echo $(( $(cat "$_ZENLOG_TIME_INJECTION_FILE") + $num )) > "$_ZENLOG_TIME_INJECTION_FILE"
}

stty -echo

# Override it.
ZENLOG_PID=$_ZENLOG_LOGGER_PID
