#!/bin/bash

cat <<'EOF'

export ZENLOG_VIEWER=${ZENLOG_VIEWER:-less}

export ZENLOG_BIN="${ZENLOG_BIN:-zenlog}"

# Install the basic shell helper functions.
. <("$ZENLOG_BIN" sh-helper)

#==============================================================================
# Functions for hot keys.
#==============================================================================

zenlog_open_last_log() {
  "$ZENLOG_BIN" open-current-log
}

zenlog_open_selected_log() {
  "$ZENLOG_BIN" open-log
}

zenlog_open_raw_with_browser() {
  local log="$1"
  local temp="$(tempfile)"

  zenlog a2h-wrapper "$log" > "$temp" || return 1
  "${ZENLOG_RAW_VIEWER:-google-chrome}" "$temp"
}

zenlog_open_last_raw() {
  zenlog_open_raw_with_browser "$("$ZENLOG_BIN" current-log -r)"
}

zenlog_open_selected_raw() {
  zenlog_open_raw_with_browser "$("$ZENLOG_BIN" select-log -r)"
}

EOF
