#!/bin/bash

# Print last log file, without the command line.
#
# Supported options: -p PID, -r

set -e
script_dir="${0%/*}"

"${script_dir}"/zenlog fail-unless-in-zenlog

sed -e 1d -- "$("${script_dir}"/zenlog last-log "${@}")"
