#!/bin/bash

cat <<'EOF'

#==============================================================================
# Simple setup script for Bash.
#
# Add the following line to your $HOME/.bashrc file.
#
# . <(zenlog basic-bash-setup)
#==============================================================================

EOF

zenlog basic-xsh-setup

cat <<'EOF'

#==============================================================================
# Pre/post exec hooks to tell when commands start and end.
#==============================================================================

zenlog_bash_basic_prompt_command() {
    local last_status=$?
    local lines=$(zenlog_bash_postexec -n "$last_status")
    echo "[rc=$last_status log=$($ZENLOG_BIN current-log) (${lines:-n/a} lines) $(pwd)]"
}

zenlog_bash_basic_ps0() {
    zenlog_bash_preexec
}

PROMPT_COMMAND="zenlog_bash_basic_prompt_command"
PS0='$(zenlog_bash_basic_ps0)'

#==============================================================================
# Set up hot keys.
# - Press ALT+1 on prompt to open the last log.
# - Press ALT+2 on prompt to open the last log file on the web browser *with color*.
#   (Must install a2h.)


bind -x '"\e1": "open_last_log"'
bind -x '"\e2": "open_last_raw"'

EOF
