#!/bin/bash

# zenlog init: Initialize ~/.zenlog.toml and ~/.bashrc/ or ~/.zshrc.

set -e

msg() {
    echo "zenlog-init: $*"
}

ask() {
    local res
    echo -n "zenlog-init: $* [Y/n]: "
    read res
    [[ "$res" == "" || "$res" == y || "$res" == Y ]]
}

#==========================================================
# Maybe create ~/.zenlog.toml

toml_to=$HOME/.zenlog.toml
toml_from=$(zenlog zenlog-src-top)/dot_zenlog.toml

if [[ ! -e "$toml_to" ]] ; then
    if ask "Wish to create file '$toml_to'?"; then
        cp "$toml_from" "$toml_to"
    fi
fi

#==========================================================
# Maybe add "basic setup" to the shell's RC file.

maybe_add_to_rc() {
    local file="$1" command="$2"

    if [[ -e "$file" ]] ;then
        if grep -q "$command" -- "$file"; then
            return 0 # Already added.
        fi
    fi

    if ask "Wish to add '$command' to '$file'?"; then
        cat >>"$file" <<EOF
# Set up zenlog.
# Note the following command does *not* start a zenlog session.
# Type "zenlog" manually to start one, or change your terminal app's setting
# to start zenlog instead of your login shell.
#
# Uncomment the following line to suppress zenlog default prompt.
# ZENLOG_NO_DEFAULT_PROMPT=1
#
# Uncomment the following line to suppress zenlog default key bindings.
# ZENLOG_NO_DEFAULT_BINDING=1
#

# Open log files in this command.
ZENLOG_VIEWER=less

# Open raw log in this command. (Requires A2H.)
ZENLOG_RAW_VIEWER=google-chrome

. <($command)
EOF
    fi
}

case "$(basename $SHELL)" in
    bash)
        maybe_add_to_rc "$HOME/.bashrc" 'zenlog basic-bash-setup'
        ;;
    zsh)
        maybe_add_to_rc "$HOME/.zshrc" 'zenlog basic-zsh-setup'
        ;;
    *)
        echo "Unknown shell $SHELL" 1>&2
        exit 1
        ;;
esac

#==========================================================


if zenlog in-zenlog ; then
    echo "Now type 'exit 13' to restart a zenlog session."
else
    echo "Now type 'zenlog' to start a zenlog session."
fi

echo

exit 0