#!/bin/bash

# Open log file selected with fzf with ZENLOG_VIEWER.
#
# Supported options: -r [open RAW] -e [open ENV]

set -e

file=$(zenlog all-commands "$@" | zenlog fzf-wrapper --tac '--nth=2..' '--with-nth=2..' '--preview=cat {1}' | awk '{print $1}')

if [[ -z "$file" ]] ; then
    exit 1
fi

zenlog flush-all

zenlog open-viewer "$file"
