#!/bin/bash

# Open log file selected with fzf with ZENLOG_VIEWER.
#
# Supported options: -r [open RAW] -e [open ENV]

set -e

file=$(zenlog select-log "$@")

if [[ -z "$file" ]] ; then
    exit 1
fi

zenlog flush-all

zenlog open-viewer "$file"
