#!/bin/bash

cat <<'EOF'

#==============================================================================
# Simple setup script for Zsh.
#
# Add the following line to your $HOME/.zrc file.
#
# . <(zenlog basic-zsh-setup)
#==============================================================================

EOF

zenlog basic-xsh-setup

cat <<'EOF'

#==============================================================================
# Set up hot keys.
# - Press ALT+1 on prompt to open the last log.
# - Press ALT+2 on prompt to open the last log file on the web browser *with color*.
#   (Must install a2h.)
# - Press ALT+3 / ALT+4 Similar, but select a log with FZF.
#==============================================================================

zle -N zenlog_open_last_log
zle -N zenlog_open_last_raw
zle -N zenlog_open_selected_log
zle -N zenlog_open_selected_raw

if [[ "$ZENLOG_NO_DEFAULT_BINDING" != "1" ]] ; then
    bindkey "\e1" zenlog_open_last_log
    bindkey "\e2" zenlog_open_last_raw
    bindkey "\e3" zenlog_open_selected_log
    bindkey "\e4" zenlog_open_selected_raw
fi

#==============================================================================
# Pre/post exec hooks.
#==============================================================================

zenlog_zsh_basic_precmd() {
    local last_status=$?
    local lines=$(zenlog_zsh_postexec -n "$last_status")

    zenlog_last_info $last_status "$(zenlog current-log)" "$lines"
}

if zenlog in-zenlog && [[ "$ZENLOG_NO_DEFAULT_PROMPT" != "1" ]] ; then
    precmd_functions=(zenlog_zsh_basic_precmd "$precmd_functions[@]")
    preexec_functions+=(zenlog_zsh_preexec)
fi

EOF
