#!/bin/bash

zenlog sh-helper

cat <<'EOF'

#==============================================================================
# Zenlog compatibility shell functions that provide functions that
# zenlog(v1) -s provided.
#==============================================================================

zenlog_echo_command() {
  zenlog show-command "$@"
}

zenlog_fail_if_not_in_zenlog() {
  zenlog fail-unless-in-zenlog
}

zenlog_history() {
  zenlog history "$@"
}

zenlog_open_viewer() {
  zenlog open-viewer "${@}"
}

zenlog_open_last_log() {
  zenlog open-last-log "${@}"
}

zenlog_cat_last_log() {
  zenlog cat-last-log "${@}"
}

zenlog_cat_last_log_content() {
  zenlog cat-last-log-content "${@}"
}

zenlog_open_current_log() {
  zenlog open-current-log "${@}"
}

zenlog_outer_tty() {
  zenlog outer-tty
}
EOF
