#!/bin/bash

# Open last log file with ZENLOG_VIEWER.
#
# Supported options: -p PID, -r [open RAW] -e [open ENV]

set -e

zenlog fail-unless-in-zenlog

zenlog flush-all

zenlog open-viewer "$(zenlog last-log "${@}")"
