#!/bin/bash

# Open current log file with ZENLOG_VIEWER.
# Useful used with -p.
#
# Supported options: -p PID, -r [open RAW] -e [open ENV]

set -e

zenlog fail-unless-in-zenlog

zenlog flush-all

zenlog open-viewer "$(zenlog current-log "${@}")"
