#!/bin/bash

# Open the given filename in ZENLOG_VIEWER.

set -e

file="$1"

if [[ -z "$file" ]]; then
    echo "zenlog open-viewer: Missing filename." 1>&2
    exit 1
fi

echo "zenlog: Opening $file ..."

"${ZENLOG_VIEWER:-$PAGER}" "$file"
