#!/bin/bash

# Show all running zenlog PIDs.
# Note this command just uses the named pipe filenames. If there was a zenlog
# that didn't close cleanly, this command might pick it up.

dir="$(zenlog temp-dir)"

for pid in $(ls "$dir/zenlog".*{f,r}.pipe | sed -e 's/^.*zenlog\.//; s/[fr]\.pipe$//' | sort -nu) ; do
    if [[ -d /proc/ ]] && ! [[ -d /proc/$pid/  ]] ; then
        # TODO Maybe also check if it's actually a zenlog process.
        rm -f "$dir/zenlog.$pid"{f,r}".pipe"
        continue
    fi
    echo $pid
done