#!/bin/bash

if (( (BASH_VERSINFO[0] < 4) || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4) )); then
    echo "Zenlog requires Bash 4.4 or above."
    exit 1
fi

cat <<'EOF'

#==============================================================================
# Simple setup script for Bash.
#
# Add the following line to your $HOME/.bashrc file.
#
# . <(zenlog basic-bash-setup)
#==============================================================================

EOF

zenlog basic-xsh-setup

cat <<'EOF'

#==============================================================================
# Set up hot keys.
# - ALT+1 on prompt to open the last log.
# - ALT+2 on prompt to open the last log file on the web browser *with color*.
#   (Must install a2h.)
# - ALT+3 / ALT+4 Similar, but select a log with FZF.
# - ALT+L inserts the last log filename at the current cursor pos.
#   Press it multiple times to recall older log files.
#==============================================================================

if [[ "$ZENLOG_NO_DEFAULT_BINDING" != "1" ]] ; then
    bind -x '"\e1": "zenlog_open_last_log"'
    bind -x '"\e2": "zenlog_open_last_raw"'
    bind -x '"\e3": "zenlog_open_selected_log"'
    bind -x '"\e4": "zenlog_open_selected_raw"'
    bind -x '"\el": "zenlog_evaler zenlog insert-log-bash"'
fi

#==============================================================================
# Pre/post exec hooks to tell when commands start and end.
#==============================================================================

zenlog_bash_basic_prompt_command() {
    local last_status=$?
    local lines=$(zenlog_bash_postexec -n "$last_status")

    zenlog in-zenlog && zenlog check-bin-update

    zenlog_last_info $last_status "$(zenlog current-log)" "$lines"
}

zenlog_bash_basic_ps0() {
    zenlog_bash_preexec
}

if zenlog in-zenlog && [[ "$ZENLOG_NO_DEFAULT_PROMPT" != "1" ]] ; then
    ZENLOG_PREV_PROMPT_COMMAND="$PROMPT_COMMAND"
    PROMPT_COMMAND="zenlog_bash_basic_prompt_command"
    PS0="${PS0}"'$(zenlog_bash_basic_ps0 >/dev/null)'
fi

EOF
