#!/bin/bash

# Show all running zenlog PIDs.
# Note this command just uses the named pipe filenames. If there was a zenlog
# that didn't close cleanly, this command will pick it up.

ls "$(zenlog temp-dir)"/zenlog.*f.pipe | sed -e 's/^.*zenlog\.//; s/f\.pipe$//'