#!/bin/bash

# Basic Zenlog bash helper functions.

# Install it with:
# . <(zenlog sh-helper)

cat <<'EOF'

# Run a command without logging the output.
function _zenlog_nolog() {
  "${@}"
}
alias 184=_zenlog_nolog

# For backward compatibility.
function zenlog_in_zenlog() {
  zenlog in-zenlog
}

# For backward compatibility.
function in_zenlog() {
  zenlog in-zenlog
}

# Run a command with forcing log, regardless of ZENLOG_ALWAYS_184_COMMANDS.
function _zenlog_force_log() {
  "${@}"
}
alias 186=_zenlog_force_log

# For backward compatibility.
function zenlog_current_log() {
  zenlog current-log "$@"
}

# For backward compatibility.
function zenlog_last_log() {
  zenlog last-log "$@"
}

# Print the current command's command line.  Use with "zenlog start-command".
function bash_last_command() {
  # Use echo to remove newlines.
  HISTTIMEFORMAT= history 1 | sed -e 's/^ *[0-9][0-9]* *//'
}

function bash_dump_env() {
  {
    echo "PWD: $(pwd)"
    echo "git HEAD: $(git rev-parse HEAD) $(git rev-parse --abbrev-ref HEAD)"
    env # dump environmental variables.
    # declare -p # this dumps shell variables too, but also functions, and may be too big.
  } 2>/dev/null
}

EOF
