package envs

const (
	ZENLOG_CONF = "ZENLOG_CONF"

	ZENLOG_PID        = "ZENLOG_PID"
	ZENLOG_SIGNATURE  = "ZENLOG_SIGNATURE"
	ZENLOG_DIR        = "ZENLOG_DIR"
	ZENLOG_TEMP       = "ZENLOG_TEMP"
	ZENLOG_AUTOFLUSH  = "ZENLOG_AUTO_FLUSH"
	ZENLOG_OUTER_TTY  = "ZENLOG_OUTER_TTY"
	ZENLOG_LOGGER_IN  = "ZENLOG_LOGGER_IN"
	ZENLOG_LOGGER_OUT = "ZENLOG_LOGGER_OUT"
)
